# $OpenBSD$

COMMENT =		extension for computing string edit distances

MODPY_EGG_VERSION =	0.12.0
DISTNAME =		python-Levenshtein-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME:L}

MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}

CATEGORIES =		devel

HOMEPAGE =		https://github.com/ztane/python-Levenshtein

MAINTAINER =		Aisha Tammy <openbsd@aisha.cc>

# GPL
PERMIT_PACKAGE =	Yes

MODPY_PI =		Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

NO_TEST =		Yes

.include <bsd.port.mk>
