COMMENT =		extension for computing string edit distances

MODPY_EGG_VERSION =	0.25.1

GH_ACCOUNT =		rapidfuzz
GH_PROJECT =		Levenshtein
GH_TAGNAME =		v${MODPY_EGG_VERSION}

PKGNAME =		py-${DISTNAME:L}

CATEGORIES =		devel

MAINTAINER =		Aisha Tammy <aisha@openbsd.org>

# GPL
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

BUILD_DEPENDS =		lang/cython

#NO_TEST =		Yes

.include <bsd.port.mk>
