# $OpenBSD$

COMMENT =	Sphinx API for Web Apps

MODPY_EGG_VERSION =	1.2.4

DISTNAME =	sphinxcontrib-websupport-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	textproc www

HOMEPAGE =	http://sphinx-doc.org/

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=	python3

.include <bsd.port.mk>
