# $OpenBSD $

COMMENT =	command line pastebin for sharing terminal output.

DISTNAME =	fiche-0.9.2

GH_ACCOUNT =	solusipse
GH_PROJECT =	fiche
GH_COMMIT =	4bba916e0f4a54d98a3947df7e2d0714d92a8bab

CATEGORIES =	net

HOMEPAGE =	https://termbin.com/

MAINTAINER =	Aisha Tammy <openbsd@aisha.cc>

PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
