     SUBDIR =
     SUBDIR += chyrp-lite
#     SUBDIR += ntfy
     SUBDIR += py-a2wsgi,python3
     SUBDIR += py-baize,python3
     SUBDIR += py-email-validator,python3
     SUBDIR += py-fastapi,python3
     SUBDIR += py-flask-babel,python3
     SUBDIR += py-starlette,python3
     SUBDIR += py-uvicorn,python3
     SUBDIR += uptime-kuma

.include <bsd.port.subdir.mk>
