COMMENT =		themes for the pallets projects

MODPY_EGG_VERSION =	2.1.3

GH_ACCOUNT =		pallets
GH_PROJECT =		pallets-sphinx-themes
GH_TAGNAME =		${MODPY_EGG_VERSION}

PKGNAME =		py-${DISTNAME}

CATEGORIES =		textproc devel

HOMEPAGE =		https://github.com/pallets/pallets-sphinx-themes

MAINTAINER =		Aisha Tammy <openbsd@aisha.cc>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PYBUILD =		flit_core

# no tests in package
NO_TEST =		Yes

.include <bsd.port.mk>
