# $OpenBSD$

COMMENT =		themes for the pallets projects

MODPY_EGG_VERSION =		1.2.3
DISTNAME =		Pallets-Sphinx-Themes-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME:L}

MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}

CATEGORIES =		textproc devel

HOMEPAGE =		https://github.com/pallets/pallets-sphinx-themes

MAINTAINER =		Aisha Tammy <openbsd@aisha.cc>

# BSD
PERMIT_PACKAGE =	Yes

MODPY_PI =		Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

NO_TEST =		Yes

.include <bsd.port.mk>
