# $OpenBSD$

COMMENT =	extension for computing string edit distances
DISTNAME = py-comicapi-0.0pre20202305
PKGNAME =	${DISTNAME:L}

GH_ACCOUNT =	OzzieIsaacs
GH_PROJECT =	comicapi
GH_COMMIT  =	3e15b950b72724b1b8ca619c36580b5fbaba9784

MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

CATEGORIES =	net

HOMEPAGE =	https://github.com/OzzieIsaacs/comicapi

MAINTAINER =	Aisha Tammy <openbsd@aisha.cc>

# Apache-2
PERMIT_PACKAGE =	Yes

MODULES =	lang/python

MODPY_PI =	Yes

MODPY_SETUPTOOLS =	Yes

NO_TEST =	Yes

.include <bsd.port.mk>
