COMMENT =	extension for computing string edit distances

DIST_TUPLE =	github OzzieIsaacs comicapi 3e15b950b72724b1b8ca619c36580b5fbaba9784 .
PKGNAME =	py-comicapi-0.0pre20200523

CATEGORIES =	net

MAINTAINER =	Aisha Tammy <aisha@openbsd.org>

# Apache-2
PERMIT_PACKAGE =	Yes

MODULES =	lang/python

MODPY_PYBUILD =	setuptools

NO_TEST =	Yes

.include <bsd.port.mk>
