# $OpenBSD$

COMMENT =	The RFC 2045 encodings; base64 and quoted-printable

DISTNAME =	MIME-Base64-3.15

CATEGORIES =	mail

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

.include <bsd.port.mk>
