# $OpenBSD$

COMMENT =	fork of Python 2 and 3 ast modules with type comment support

MODPY_EGG_VERSION =	1.4.1

DISTNAME =	typed_ast-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	devel

HOMEPAGE =	https://github.com/python/typed_ast

MAINTAINER =		Aisha Tammy <openbsd@aisha.cc>

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =		python3
FLAVOR ?=		python3

.include <bsd.port.mk>
