# $OpenBSD $

COMMENT =	neomutt and isync configuration with good defaults
DISTNAME = mutt-wizard-0.0.20200531
CATEGORIES =	mail

GH_ACCOUNT =	LukeSmithxyz
GH_PROJECT =	mutt-wizard
GH_COMMIT  =	bb72cf5a71418a3d8eaa3cc731a2b8a8627e9c1c

MAINTAINER =	Aisha Tammy <openbsd@aisha.cc>

# GPL-3
PERMIT_PACKAGE =	Yes

RUN_DEPENDS =	mail/neomutt \
		mail/isync \
		mail/msmtp \
		security/password-store

NO_BUILD =	Yes
NO_TEST =	Yes
USE_GMAKE =	Yes

.include <bsd.port.mk>
