# $OpenBSD$

COMMENT =		tool to build manual page from ArgumentParser

MODPY_EGG_VERSION =	1.5
DISTNAME =		argparse-manpage-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME:L}

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/praiskup/argparse-manpage

MAINTAINER =		Aisha Tammy <openbsd@aisha.cc>

# BSD
PERMIT_PACKAGE =	Yes

MODPY_PI =		Yes

MODULES =		lang/python
FLAVORS =		python3
FLAVOR ?=		python3

MODPY_SETUPTOOLS =	Yes

MODPY_PYTEST =		Yes

.include <bsd.port.mk>
